### ISSUE TITLE
[bug] currentToolId not updating when setting selected tool

### ISSUE THREAD

**Issue by cristianpjensen** [tldraw/tldraw-examples#4]
Hi, I am using the alpha v2 library. 

I've run into an issue with using custom shapes in my custom UI. I have defined my custom shape and tool as in the custom config example. I have also set up my custom UI as in the custom UI example. However, when calling `app.setSelectedTool(<custom-tool>)`, it does not update `app.currentToolId`. But, the weird thing is that the current tool has been updated, because when I try to use it on the canvas, it does behave as if the new tool is selected. But, the current tool variable does not get updated, so it does not show up as selected in my custom toolbar.

By the way, the other default tools do work still and `app.currentToolId` does get updated appropriately.

I have also tried using the underlying atom `app._currentToolId.value`, but that variable also does not get updated appropriately. I am wondering where the current tool does update, since it does get selected and is usable; the variable just doesn't get updated.

Thanks.

**Comment by ds300** [comment]
Hi! Are you on the latest alpha version of the package? A few people had this same issue last week and it was because we had our dependencies set up wrong which caused signia, the tool we use to handle reactivity, to be duplicated in folks' app bundles. Both `signia` and `signia-react`  are now peer dependencies, so you should add them to your app's package.json and that should prevent duplicates from appearing in your bundle.

The other thing to know is that in order to use the reactive values in react components you need to use either `track` or `useValue` from the `signia-react` package to make sure your components are [reactive](https://signia.tldraw.dev/docs/react-bindings#writing-reactive-components).

If you've already done that and you're still having issues it would be good to know a little more about your setup to help diagnose. If you can share a link to your repo, that'd be ideal!

**Comment by cristianpjensen** [comment]
Hi, I am using `@tldraw/tldraw 2.0.0-alpha.8`. I think this is the latest update (at least according to npm it is). I am also using versions `0.1.0` for `signia` and `signia-react` and they are added to my package.json. But, I still have the same issue.

The code for my toolbar likes like the following:
```tsx
import { useApp } from "@tldraw/tldraw";
import { track } from "signia-react";
import * as RadixToolbar from "@radix-ui/react-toolbar";
import { Icon, IconName } from "../components";

const Toolbar = track(() => {
    const app = useApp();
    return (
        <RadixToolbar.Root>
            <RadixToolbar.ToggleGroup
                type="single"
                value={app.currentToolId}
                className="ui__toolbar"
            >
                <ToolbarButton tool="figure" icon="rectangle" />
                <ToolbarButton tool="select" icon="cursor" />
                <ToolbarButton tool="hand" icon="hand" />
                <ToolbarButton tool="draw" icon="pencil" />
                <ToolbarButton tool="eraser" icon="eraser" />
                <ToolbarButton tool="rectangle" icon="rectangle" />
                <ToolbarButton tool="ellipse" icon="ellipse" />
                <ToolbarButton tool="bezier" icon="pen" />
                <ToolbarButton tool="text" icon="text" />
                <ToolbarButton tool="maths" icon="maths" />
            </RadixToolbar.ToggleGroup>
        </RadixToolbar.Root>
    );
});

interface ToolbarButtonProps {
    tool: string;
    icon: IconName;
}

const ToolbarButton = track(({ tool, icon }: ToolbarButtonProps) => {
    const app = useApp();
    return (
        <RadixToolbar.ToggleItem
            value={tool}
            className="ui__toolbar__button"
            onClick={() => app.setSelectedTool(tool)}
        >
            <Icon name={icon} />
        </RadixToolbar.ToggleItem>
    );
});

export { Toolbar };
```

I am using `track`, so I am not sure what the issue is. It is also odd that it does work for the predefined tools, but not for my custom tool.

The repository can be found here: https://github.com/cristianpjensen/figur.

**Comment by cristianpjensen** [comment]
I should have been a little more clear, but I was not referring to rectangle. (I am actually planning on making my own rectangle shape :).) I actually forgot to commit what I was trying with the custom shape and tool I had registered with Tldraw, sorry. I have committed it now.

I register the shape and tool in `App.tsx`:
```tsx
type FigureShape = TLBaseShape<
    "figure",
    {
        w: number;
        h: number;
    }
>;

export const FigureShape = defineShape<FigureShape>({
    type: "figure",
    getShapeUtil: () => FigureUtil,
});

class FigureUtil extends TLBoxUtil<FigureShape> {
    static type = "figure";

    override isAspectRatioLocked = () => false;
    override canBind = () => false;

    defaultProps(): FigureShape["props"] {
        return {
            w: 100,
            h: 100,
        };
    }

    render(shape: FigureShape) { ... }
    indicator(shape: FigureShape) { ... }
}

class FigureTool extends TLBoxTool {
    static id = "figure";
    static initial = "idle";
    shapeType = "figure";
}

const config = new TldrawEditorConfig({
    tools: [FigureTool],
    shapes: [FigureShape],
    allowUnknownShapes: true,
});

function App() {
    return (
        <div className="editor">
            <TldrawEditor config={config}>
                <Canvas />
                <UserInterface />
            </TldrawEditor>
        </div>
    );
}
```

And, I change the tool in `ui/toolbar.tsx`:
```tsx
import { useApp } from "@tldraw/tldraw";
import { track } from "signia-react";
import * as RadixToolbar from "@radix-ui/react-toolbar";
import { Icon, IconName } from "../components";

const Toolbar = track(() => {
    const app = useApp();
    return (
        <RadixToolbar.Root>
            <RadixToolbar.ToggleGroup
                type="single"
                value={app.currentToolId}
                className="ui__toolbar"
            >
                <ToolbarButton tool="figure" icon="rectangle" />
                ...
            </RadixToolbar.ToggleGroup>
        </RadixToolbar.Root>
    );
});

interface ToolbarButtonProps {
    tool: string;
    icon: IconName;
}

const ToolbarButton = track(({ tool, icon }: ToolbarButtonProps) => {
    const app = useApp();
    return (
        <RadixToolbar.ToggleItem
            value={tool}
            className="ui__toolbar__button"
            onClick={() => app.setSelectedTool(tool)}
        >
            <Icon name={icon} />
        </RadixToolbar.ToggleItem>
    );
});

export { Toolbar };
```

The problem is that `app.currentToolId` does not get updated when I click on the toolbar button for the `figure` tool. But, it does get updated when I click on the toolbar button for the `draw` tool or `text` tool, which are already implemented. The weird thing is that when I click on the `figure` tool button, it does update the tool, because I can use the tool, but it does not update `app.currentToolId`. Another thing I noticed is that when I use the `figure` tool once (in this weird state where `app.currentToolId != "figure"`) it immediately goes back to the `select` tool.

I hope this is a clear explanation of what is going on.

Sorry again for not updating my repository... :(
